name = "sat-water-temps-worker"
main = "worker/src/index.ts"
compatibility_date = "2024-05-01"
account_id = "6df78a6dde66ef6f6ef937de5dc8e407"

r2_buckets = [
  { binding = "R2_DATA", bucket_name = "multitifs", preview_bucket_name = "multitifs-dev" }
]

# Uncomment and set your route/zone for production
# routes = [
#   { pattern = "api.example.com/*", zone_name = "example.com" }
# ]

# If serving APIs under a subpath, set a custom service binding and route accordingly.
